openapi: 3.1.0
info:
  title: Open Payments
  version: '1.0'
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  description: |-
    The Open Payments API is a simple REST API with 4 resource types: **account**, **account holder**, **incoming payment** and **outgoing payment**.  

    The *service endpoint* for the API is always the URL of the account resource and all other resources are sub-resources of the account.  

    All resource and collection resource representations use JSON and the media-type `application/json`.  

    The `account` resource has two collections of sub-resources and a single **account holder** sub-resource:   
    1. `/incoming-payments` contains the **incoming payment** sub-resources  
    2. `/outgoing-payments` contains the **outgoing payment** sub-resources  
    3. `/holder` contains the **outgoing payment** sub-resources  

    Access to resources and permission to execute the methods exposed by the API is determined by the grants given to the client represented by an access token used in API requests.
  summary: An API for open access to financial accounts to send and receive payments.
servers:
  - url: 'https://openpayments.guide/alice'
    description: alice
  - url: 'https://openpayments.guide/bob'
    description: bob
paths:
  /:
    get:
      summary: Get a Payment Pointer
      tags: []
      responses:
        '200':
          description: Account Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
              examples:
                Get account for $openpayments.guide/alice:
                  value:
                    id: 'https://openpayments.guide/alice'
                    publicName: Alice
                    assetCode: USD
                    assetScale: 2
                    authServer: 'https://openpayments.guide/auth'
        '404':
          description: Account Not Found
      operationId: get-public-account
      description: |-
        Retrieve the public information of the account represented by the Payment Pointer.

        This end-point should be open to anonymous requests as it allows clients to verify a Payment Pointer URL and get the basic information required to construct new transactions and discover the grant request URL.

        The content should be slow changing and cacheable for long periods. Servers SHOULD use cache control headers.
      security: []
  /incoming-payments:
    post:
      summary: Create an Incoming Payment
      tags: []
      operationId: create-incoming-payment
      responses:
        '201':
          description: Incoming Payment Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
              examples:
                New Incoming Payment for $25:
                  value:
                    id: 'http://openpayments.guide/alice/incoming-payments/08394f02-7b7b-45e2-b645-51d04e7c330c'
                    accountId: 'http://openpayments.guide/alice/'
                    state: pending
                    incomingAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      amount: 0
                      assetCode: USD
                      assetScale: 2
                    expiresAt: '2022-02-03T23:20:50.52Z'
                    externalRef: INV2022-02-0137
                    ilpApddress: g.ilp.iwuyge987y.98y08y
                    sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                incomingAmount:
                  $ref: '#/components/schemas/amount'
                expiresAt:
                  type: string
                  description: The date and time when payments into the incoming payment must no longer be accepted.
                  format: date-time
                  writeOnly: true
                description:
                  type: string
                  description: Human readable description of the incoming payment that will be visible to the account holder.
                externalRef:
                  type: string
                  description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
            examples:
              Create incoming payment for $25 to pay invoice INV2022-02-0137:
                value:
                  incomingAmount:
                    amount: 2500
                    assetCode: USD
                    assetScale: 2
                  externalRef: INV2022-02-0137
        description: |-
          A subset of the incoming payments schema is accepted as input to create a new incoming payment.

          If provided, the `incomingAmount` must use the same `assetCode` and `assetScale` as the account.
      description: |-
        A client MUST create an **incoming payment** resource before it is possible to send any payments to the account. 

        All of the input parameters are _optional_.
    get:
      summary: List Incoming Payments
      operationId: list-incoming-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list-incoming-payments'
              examples:
                forward pagination:
                  value:
                    pagination:
                      startCursor: 241de237-f989-42be-926d-c0c1fca57708
                      endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                      hasNextPage: true
                      first: 10
                    result:
                      - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        incomingAmount:
                          amount: 250
                          assetCode: USD
                          assetScale: 2
                        receivedAmount:
                          amount: 250
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
                        externalRef: Coffee w/ Mo on 10 March 22
                        ilpApddress: g.ilp.iwuyge987y.98y08y
                        sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
                      - id: 'https://openpayments.guide/alice/incoming-payments/32abc219-3dc3-44ec-a225-790cacfca8fa'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        receivedAmount:
                          amount: 100
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-13T10:23:52.50Z'
                        description: 'I love your website, Alice! Thanks for the great content'
                        ilpApddress: g.ilp.98y08yiwuy.ge987y
                        sharedSecret: IVRvqeasJeCty66jR5iNC+YB5X9FhSOUPCL/5nha5Vs=
                backward pagination:
                  value:
                    pagination:
                      startCursor: 241de237-f989-42be-926d-c0c1fca57708
                      endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                      hasPreviousPage: true
                      last: 10
                    result:
                      - id: 'https://openpayments.guide/alice/incoming-payments/32abc219-3dc3-44ec-a225-790cacfca8fa'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        receivedAmount:
                          amount: 100
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-13T10:23:52.50Z'
                        description: 'I love your website, Alice! Thanks for the great content'
                        ilpApddress: g.ilp.98y08yiwuy.ge987y
                        sharedSecret: IVRvqeasJeCty66jR5iNC+YB5X9FhSOUPCL/5nha5Vs=
                      - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
                        accountId: 'https://openpayments.guide/alice/'
                        state: completed
                        incomingAmount:
                          amount: 250
                          assetCode: USD
                          assetScale: 2
                        receivedAmount:
                          amount: 250
                          assetCode: USD
                          assetScale: 2
                        expiresAt: '2022-04-12T23:20:50.52Z'
                        description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
                        externalRef: Coffee w/ Mo on 10 March 22
                        ilpApddress: g.ilp.iwuyge987y.98y08y
                        sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
          headers: {}
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      description: List all incoming payments on the account
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
            default: 10
          in: query
          name: first
          description: 'The number of items to return, forward pagination'
        - schema:
            type: integer
            default: 10
            example: 10
            minimum: 1
            maximum: 100
          in: query
          name: last
          description: 'The number of items to return, backward pagination'
        - schema:
            type: string
            example: gwe867t2frof
          in: query
          name: cursor
          description: The cursor key to list from
  /outgoing-payments:
    post:
      summary: Create an Outgoing Payment
      tags: []
      operationId: create-outgoing-payment
      responses:
        '201':
          description: Outgoing Payment Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outgoing-payment'
              examples:
                New Fixed Send Outgoing Payment for $25:
                  value:
                    id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                    accountId: 'https://openpayments.guide/alice/'
                    state: prepared
                    authorized: false
                    receivingAccount: 'https://openpayments.guide/bob/'
                    sendAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    fundsAvailable: true
                    expiresAt: '2022-04-12T23:20:50.52Z'
                    description: Thank you for the shoes.
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      requestBody:
        content:
          application/json:
            examples:
              Create fixed-send-amount outgoing payment for $25 to pay invoice INV2022-02-0137:
                value:
                  receivingAccount: 'https://openpayments.guide/alice'
                  sendAmount:
                    amount: 2500
                  externalRef: INV2022-02-0137
              Create fixed-receive-amount outgoing payment for $25 to pay invoice INV2022-02-0137:
                value:
                  receivingAccount: 'https://openpayments.guide/alice'
                  receiveAmount:
                    amount: 2500
                  externalRef: INV2022-02-0137
            schema:
              type: object
              properties:
                authorized:
                  type: boolean
                  description: Indicates if the payment is authorized to begin processing.
                  default: false
                receivingAccount:
                  type: string
                  format: uri
                  description: The URL of the account that is being paid.
                receivingPayment:
                  type: string
                  format: uri
                  description: The URL of the incoming payment that is being paid.
                receiveAmount:
                  $ref: '#/components/schemas/amount'
                sendAmount:
                  $ref: '#/components/schemas/amount'
                fundsAvailable:
                  type: boolean
                  description: Indicates that there are funds available in the underlying account to complete this payment. This is not a guarantee they will still be available when the payment is attempted but it is a good indicator to a client that it should attempt to authorize the payment.
                  readOnly: true
                expiresAt:
                  type: string
                  description: The date and time when the calculated `sendAmount` is no longer valid.
                  readOnly: true
                description:
                  type: string
                  description: Human readable description of the outgoing payment that will be visible to the account holder and shared with the receiver.
                externalRef:
                  type: string
                  description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
        description: |-
          A subset of the outgoing payments schema is accepted as input to create a new outgoing payment.

          If provided, the `sendAmount` must use the same `assetCode` and `assetScale` as the account.
      description: An **outgoing payment** is a sub-resource of an account. It represents a payment from the account.
    description: Create a new outgoing payment at the account.
    get:
      summary: List Outgoing Payments
      operationId: list-outgoing-payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/list-outgoing-payments'
              examples:
                forward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasNextPage: true
                        first: 10
                      result:
                        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          state: completed
                          authorized: true
                          receivingAccount: 'https://openpayments.guide/aplusvideo/'
                          receiveAmount:
                            amount: 2500
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            amount: 2500
                            assetCode: USD
                            assetScale: 2
                          fundsAvailable: true
                          expiresAt: '2022-04-12T23:20:50.52Z'
                          description: APlusVideo subscription
                          externalRef: 'customer: 847458475'
                        - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          state: completed
                          authorized: true
                          receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            amount: 7026
                            assetCode: USD
                            assetScale: 2
                          fundsAvailable: true
                          expiresAt: '2022-04-30T14:20:32.49Z'
                          description: Thank you for your purchase at ShoeShop!
                          externalRef: INV2022-8943756
                backward pagination:
                  value:
                    - pagination:
                        startCursor: 241de237-f989-42be-926d-c0c1fca57708
                        endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
                        hasPreviousPage: true
                        last: 10
                      result:
                        - id: 'https://openpayments.guide/alice/outgoing-payments/0cffa5a4-58fd-4cc8-8e01-7145c72bf07c'
                          accountId: 'https://openpayments.guide/alice/'
                          state: completed
                          authorized: true
                          receivingPayment: 'https://openpayments.guide/shoeshop/2fe92c6f-ef0d-487c-8759-3784eae6bce9'
                          sendAmount:
                            amount: 7026
                            assetCode: USD
                            assetScale: 2
                          fundsAvailable: true
                          expiresAt: '2022-04-30T14:20:32.49Z'
                          description: Thank you for your purchase at ShoeShop!
                          externalRef: INV2022-8943756
                        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
                          accountId: 'https://openpayments.guide/alice/'
                          state: completed
                          authorized: true
                          receivingAccount: 'https://openpayments.guide/aplusvideo/'
                          receiveAmount:
                            amount: 2500
                            assetCode: USD
                            assetScale: 2
                          sendAmount:
                            amount: 2500
                            assetCode: USD
                            assetScale: 2
                          fundsAvailable: true
                          expiresAt: '2022-04-12T23:20:50.52Z'
                          description: APlusVideo subscription
                          externalRef: 'customer: 847458475'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
      description: List all outgoing payments on the account
      parameters:
        - schema:
            type: integer
          in: query
          name: first
          description: 'The number of items to return, forward pagination'
        - schema:
            type: integer
          in: query
          name: last
          description: 'The number of items to return, backward pagination'
        - schema:
            type: string
          in: query
          name: cursor
          description: The cursor key to list from
  '/incoming-payments/{id}':
    get:
      summary: Get an Incoming Payment
      tags: []
      operationId: get-incoming-payment
      responses:
        '200':
          description: Incoming Payment Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
              examples:
                Incoming Payment for $25 with $12.34 received so far:
                  value:
                    id: 'https://openpayments.guide/alice/incoming-payments/2f1b0150-db73-49e8-8713-628baa4a17ff'
                    accountId: 'https://openpayments.guide/alice/'
                    state: processing
                    incomingAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receivedAmount:
                      amount: 1234
                      assetCode: USD
                      assetScale: 2
                    expiresAt: '2022-04-12T23:20:50.52Z'
                    description: Thanks for the flowers!
                    externalRef: INV-12876
                    ilpAddress: g.ilp.iwuyge987y.98y08y
                    sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Incoming Payment Not Found
      description: A client can fetch the latest state of an incoming payment to determine the amount received into the account.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Incoming Payment identifier
    put:
      summary: Update an Incoming Payment
      operationId: update-incoming-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/incoming-payment'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Incoming Payment Not Found
      description: |-
        A client with the appropriate permissions MAY update the state of an **incoming payment** to `completed` if it is in a state of `pending` or `processing`.

        This indicates to the receiving account provider that it can begin any post processing of the payment such as generating account statements or notifying the account holder of the completed payment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  example: completed
                  enum:
                    - completed
            examples:
              Complete Incoming Payment:
                value:
                  state: completed
        description: Update the state of the incoming payment to `completed`.
  '/outgoing-payments/{id}':
    get:
      summary: Get an Outgoing Payment
      tags: []
      operationId: get-outgoing-payment
      responses:
        '200':
          description: Outgoing Payment Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outgoing-payment'
              examples:
                Outgoing Payment with a fixed send amount of $25:
                  value:
                    id: 'https://openpayments.guide/bob/outgoing-payments/3859b39e-4666-4ce5-8745-72f1864c5371'
                    accountId: 'https://openpayments.guide/bob/'
                    state: processing
                    authorized: true
                    receivingPayment: 'http://openpayments.guide/alice/incoming-payments/2f1b0150-db73-49e8-8713-628baa4a17ff'
                    sendAmount:
                      amount: 2500
                      assetCode: USD
                      assetScale: 2
                    receiveAmount:
                      amount: 2198
                      assetCode: EUR
                      assetScale: 2
                    fundsAvailable: true
                    expiresAt: '2022-04-12T23:20:50.52Z'
                    description: Thanks for the flowers!
                    externalRef: INV-12876
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Incoming Payment Not Found
      description: A client can fetch the latest state of an outgoing payment.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Incoming Payment identifier
    put:
      summary: Update an Outgoing Payment
      operationId: update-outgoing-payment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/outgoing-payment'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          description: Outgoing Payment Not Found
      description: |-
        A client with the appropriate permissions MAY update an **outgoing payment** to either change the amount that was originally requested or authorize the payment.

        To authorize the payment the client updates the value of `authorized` to `true`.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                state:
                  type: string
                  example: completed
                  enum:
                    - completed
            examples:
              Authorize Outgoing Payment:
                value:
                  authorized: true
              Update Send Amount:
                value:
                  sendAmount:
                    amount: 2500
              Update Receive Amount:
                value:
                  receiveAmount:
                    amount: 512
                    assetCode: EUR
                    assetScale: 2
        description: Update the state of the incoming payment to `completed`.
components:
  schemas:
    account:
      title: Account
      type: object
      description: An **account** resource is the root of the API and contains the public details of the financial account represented by the Payment Pointer that is also the service endpoint URL.
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          example: 'https://openpayments.guide/alice'
          readOnly: true
        publicName:
          type: string
          description: A public name for the account. This should be set by the account holder with their provider to provide a hint to counterparties as to the identity of the account holder.
          example: Alice
          readOnly: true
        assetCode:
          type: string
          description: The asset code of the account. This SHOULD be an ISO4217 currency code.
          example: USD
          readOnly: true
        assetScale:
          type: integer
          description: The scale of the account.
          example: 2
          readOnly: true
        authServer:
          type: string
          format: uri
          description: The URL of the authorization server endpoint for getting grants and access tokens for this account.
          example: 'https://openpayments.guide/auth'
          readOnly: true
      examples:
        - id: 'https://openpayments.guide/alice'
          publicName: Alice
          assetCode: USD
          assetScale: 2
          authServer: 'https://openpayments.guide/auth'
    incoming-payment:
      title: Incoming Payment
      description: 'An **incoming payment** resource represents a payment that will be, is currently being, or has been received by the account.'
      type: object
      examples:
        - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
          accountId: 'https://openpayments.guide/alice/'
          state: completed
          incomingAmount:
            amount: 250
            assetCode: USD
            assetScale: 2
          receivedAmount:
            amount: 250
            assetCode: USD
            assetScale: 2
          expiresAt: '2022-04-12T23:20:50.52Z'
          description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
          externalRef: Coffee w/ Mo on 10 March 22
          ilpApddress: g.ilp.iwuyge987y.98y08y
          sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          example: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account this payment is being made into.
          example: 'https://openpayments.guide/alice/'
          readOnly: true
        state:
          type: string
          description: The state of the payment as described above.
          enum:
            - pending
            - processing
            - completed
            - expired
          example: completed
          default: pending
        incomingAmount:
          $ref: '#/components/schemas/amount'
        receivedAmount:
          $ref: '#/components/schemas/amount'
        expiresAt:
          type: string
          description: The date and time when payments into the incoming payment will no longer be accepted.
          format: date-time
          example: '2022-04-12T23:20:50.52Z'
        description:
          type: string
          description: Human readable description of the incoming payment that will be visible to the account holder.
          example: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
        externalRef:
          type: string
          description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
          example: Coffee w/ Mo on 10 March 22
        ilpApddress:
          type: string
          description: The ILP address to use when establishing a STREAM connection.
          example: g.ilp.iwuyge987y.98y08y
          readOnly: true
        sharedSecret:
          type: string
          description: The shared secret to use when establishing a STREAM connection.
          example: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
          readOnly: true
    outgoing-payment:
      title: Outgoing Payment
      description: 'An **outgoing payment** resource represents a payment that will be, is currently being, or has previously been, sent from the account.'
      type: object
      examples:
        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
          accountId: 'https://openpayments.guide/alice/'
          state: completed
          authorized: true
          receivingAccount: 'https://openpayments.guide/aplusvideo/'
          receiveAmount:
            amount: 2500
            assetCode: USD
            assetScale: 2
          sendAmount:
            amount: 2500
            assetCode: USD
            assetScale: 2
          fundsAvailable: true
          expiresAt: '2022-04-12T23:20:50.52Z'
          description: APlusVideo subscription
          externalRef: 'customer: 847458475'
        - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
          accountId: 'https://openpayments.guide/alice/'
          state: completed
          authorized: true
          receivingPayment: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
          sendAmount:
            amount: 2500
            assetCode: USD
            assetScale: 2
          fundsAvailable: true
          expiresAt: '2022-04-12T23:20:50.52Z'
          description: APlusVideo subscription
          externalRef: 'customer: 847458475'
      properties:
        id:
          type: string
          format: uri
          description: The URL identifying the incoming payment.
          example: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
          readOnly: true
        accountId:
          type: string
          format: uri
          description: The URL of the account this payment is being made into.
          example: 'https://openpayments.guide/alice/'
          readOnly: true
        state:
          type: string
          description: The state of the payment as described above.
          enum:
            - pending
            - completed
            - expired
            - failed
            - prepared
            - processing
          example: completed
          default: pending
        authorized:
          type: boolean
          description: Indicates if the payment is authorized to begin processing.
          default: false
        receivingAccount:
          type: string
          format: uri
          description: The URL of the account that is being paid.
          example: 'https://openpayments.guide/aplusvideo/'
        receivingPayment:
          type: string
          format: uri
          description: The URL of the incoming payment that is being paid.
          example: 'https://openpayments.guide/aplusvideo/incoming-payments/45d495ad-b763-4882-88d7-aa14d261686e'
        receiveAmount:
          $ref: '#/components/schemas/amount'
        sendAmount:
          $ref: '#/components/schemas/amount'
        fundsAvailable:
          type: boolean
          description: Indicates that there are funds available in the underlying account to complete this payment. This is not a guarantee they will still be available when the payment is attempted but it is a good indicator to a client that it should attempt to authorize the payment.
          readOnly: true
        expiresAt:
          type: string
          description: The date and time when the calculated `sendAmount` is no longer valid.
          example: '2022-04-12T23:20:50.52Z'
          readOnly: true
        description:
          type: string
          description: Human readable description of the outgoing payment that will be visible to the account holder and shared with the receiver.
          example: APlusVideo subscription
        externalRef:
          type: string
          description: A reference that can be used by external systems to reconcile this payment with their systems. E.g. An invoice number. (Optional)
          example: 'customer: 847458475'
    amount:
      title: Amount
      type: object
      description: |-
        All amounts in open payments are represented as an unsigned 64-bit integer amount and an asset code and scale.

        The `assetCode` is a code that indicates the underlying asset. In most cases this SHOULD be a 3-character ISO 4217 currency code.

        The `assetScale` indicates how the value of `amount` has been scaled relative to the natural scale of the asset. For example, an `amount` of `1234` with an `assetScale` of `2` represents an amount of `12.34`.
      examples:
        - amount: 2500
          assetCode: USD
          assetScale: 2
        - amount: 500
          assetCode: EUR
          assetScale: 2
        - amount: 123456789
          assetCode: BTC
          assetScale: 8
      properties:
        amount:
          type: integer
          description: The amount that must be paid into the receiver’s account.
          example: 2500
          maximum: 18446744073709552000
          minimum: 0
        assetCode:
          type: string
          description: The asset code of the amount. This SHOULD be an ISO4217 currency code.
          example: USD
        assetScale:
          type: integer
          description: The scale of the amount.
          example: 2
    pagination:
      description: ''
      type: object
      x-examples:
        example-1:
          startCursor: string
          endCursor: string
          hasNextPage: true
          hasPreviousPage: true
          limit: 0
      examples:
        - startCursor: 241de237-f989-42be-926d-c0c1fca57708
          endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
          hasNextPage: true
          hasPreviousPage: true
          first: 10
          last: 10
      properties:
        startCursor:
          type: string
          minLength: 1
          example: 241de237-f989-42be-926d-c0c1fca57708
          description: Cursor corresponding to the first element in the result array.
        endCursor:
          type: string
          minLength: 1
          example: 315581f8-9967-45a0-9cd3-87b60b6d6414
          description: Cursor corresponding to the last element in the result array.
        hasNextPage:
          type: boolean
          description: Describes whether the data set has further entries.
        hasPreviousPage:
          type: boolean
          description: Describes whether the data set has previous entries.
        first:
          type: number
          example: 10
          description: Number of entries requested using forward pagination.
        last:
          type: number
          description: Number of entries requested using backward pagination.
          example: 10
    list-incoming-payments:
      title: list-incoming-payments
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        result:
          type: array
          items:
            $ref: '#/components/schemas/incoming-payment'
      examples:
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasPreviousPage: true
            last: 10
          result:
            - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              incomingAmount:
                amount: 250
                assetCode: USD
                assetScale: 2
              receivedAmount:
                amount: 250
                assetCode: USD
                assetScale: 2
              expiresAt: '2022-04-12T23:20:50.52Z'
              description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
              externalRef: Coffee w/ Mo on 10 March 22
              ilpApddress: g.ilp.iwuyge987y.98y08y
              sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasNextPage: true
            first: 10
          result:
            - id: 'https://openpayments.guide/alice/incoming-payments/016da9d5-c9a4-4c80-a354-86b915a04ff8'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              incomingAmount:
                amount: 250
                assetCode: USD
                assetScale: 2
              receivedAmount:
                amount: 250
                assetCode: USD
                assetScale: 2
              expiresAt: '2022-04-12T23:20:50.52Z'
              description: 'Hi Mo, this is for the cappuccino I bought for you the other day.'
              externalRef: Coffee w/ Mo on 10 March 22
              ilpApddress: g.ilp.iwuyge987y.98y08y
              sharedSecret: 6jR5iNIVRvqeasJeCty6C+YB5X9FhSOUPCL/5nha5Vs=
    list-outgoing-payments:
      title: list-outgoing-payments
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/pagination'
        result:
          type: array
          items:
            $ref: '#/components/schemas/outgoing-payment'
      examples:
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasNextPage: true
            first: 10
          result:
            - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              authorized: true
              receivingAccount: 'https://openpayments.guide/aplusvideo/'
              receiveAmount:
                amount: 2500
                assetCode: USD
                assetScale: 2
              sendAmount:
                amount: 2500
                assetCode: USD
                assetScale: 2
              fundsAvailable: true
              expiresAt: '2022-04-12T23:20:50.52Z'
              description: APlusVideo subscription
              externalRef: 'customer: 847458475'
        - pagination:
            startCursor: 241de237-f989-42be-926d-c0c1fca57708
            endCursor: 315581f8-9967-45a0-9cd3-87b60b6d6414
            hasPreviousPage: true
            last: 10
          result:
            - id: 'https://openpayments.guide/alice/outgoing-payments/8c68d3cc-0a0f-4216-98b4-4fa44a6c88cf'
              accountId: 'https://openpayments.guide/alice/'
              state: completed
              authorized: true
              receivingAccount: 'https://openpayments.guide/aplusvideo/'
              receiveAmount:
                amount: 2500
                assetCode: USD
                assetScale: 2
              sendAmount:
                amount: 2500
                assetCode: USD
                assetScale: 2
              fundsAvailable: true
              expiresAt: '2022-04-12T23:20:50.52Z'
              description: APlusVideo subscription
              externalRef: 'customer: 847458475'
  securitySchemes:
    GNAP:
      name: Authorization
      type: apiKey
      in: header
      description: |-
        The API uses the Grant Negotiation and Authorization Protocol for authorization. An access token must be acquired from an authorization server before accessing the API and then provided in the request headers using the prefix `GNAP`.

        All requests must also be signed using a client key over some select headers and a digest of the request body.
  responses:
    '401':
      description: Authorization required
      headers:
        WWW-Authenticate:
          schema:
            type: string
          description: The address of the authorization server for grant requests in the format `GNAP as_uri=<URI>`
    '403':
      description: Forbidden
security:
  - GNAP: []
